# Numpy Tutorial

In [1]:
import numpy as np

In [7]:
l1 = [[1,2,3,4,5],[6,7,8,9,10]]
myarr = np.array(l1)

In [10]:
myarr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
myarr.dtype

dtype('int32')

In [9]:
print(myarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
myarr.shape

(2, 5)

In [11]:
myarr.size

10

In [21]:
zeroarray = np.zeros(5)
print(zeroarray)

[0. 0. 0. 0. 0.]


In [20]:
rangearray = np.arange(3,10)
print(rangearray)

[3 4 5 6 7 8 9]


In [26]:
# lspace = np.linspace(1,4,4)
lspace = np.linspace(1,10,4)
print(lspace)

[ 1.  4.  7. 10.]


#### For making Identity matrix

In [31]:
identity = np.identity(3) # No of rows & columns 
print(identity)
identity.shape

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


(3, 3)

#### Reshaping the array

In [37]:
arr = np.arange(50)
print(arr)
print("After reshaping the array")
arr = arr.reshape(2,25)
print(arr)
print("Making the reshaped array in 1D again")
arr = arr.ravel()
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
After reshaping the array
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]]
Making the reshaped array in 1D again
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


#### Axis concept in Array

In [42]:
x = [[1,2,3],[4,5,6],[7,1,0]]
arr = np.array(x)
arr.sum() # Sum of all elements

29

In [43]:
arr.sum(axis = 0) # Sum of elements of the columns (example: 1+4+7 = 12)

array([12,  8,  9])

In [44]:
arr.sum(axis = 1) # Sum of elements of the rows (example: 1+2+3 = 6)

array([ 6, 15,  8])

In [46]:
# Transpose
print(arr)
print("Transpose Operation")
print(arr.T)

[[1 2 3]
 [4 5 6]
 [7 1 0]]
Transpose Operation
[[1 4 7]
 [2 5 1]
 [3 6 0]]


In [53]:
maxElementIndex = np.array([10,20,7865,1151,4,5,6])
maxElementIndex.argmax() # returns the index of the maximum element

2

In [54]:
maxElementIndex.argmin() # returns the index of the minimum element

4

In [55]:
maxElementIndex.argsort() #returns indexes of sorted list 

array([4, 5, 6, 0, 1, 3, 2], dtype=int64)

In [61]:
print(arr)
print()
print(arr.argsort()) # Same goes for n-dimensional array

[[1 2 3]
 [4 5 6]
 [7 1 0]]

[[0 1 2]
 [0 1 2]
 [2 1 0]]


In [63]:
print(arr)
print(arr.argmin())

[[1 2 3]
 [4 5 6]
 [7 1 0]]
8


In [64]:
print(arr)
print(arr.argmax())

[[1 2 3]
 [4 5 6]
 [7 1 0]]
6


#### Axis wise argmax & argmin

In [66]:
print(arr.argmax(axis=0)) # returns indexes of max elements in column

[2 1 1]


In [67]:
print(arr.argmax(axis=1)) # returns indexes of max elements in row

[2 2 0]


# Matrix Operations using Numpy

In [70]:
arr2 = np.array([[1,2,1],[4,0,6],[8,1,0]])
print(arr)
print()
print(arr2)
print()
print(arr + arr2)

[[1 2 3]
 [4 5 6]
 [7 1 0]]

[[1 2 1]
 [4 0 6]
 [8 1 0]]

[[ 2  4  4]
 [ 8  5 12]
 [15  2  0]]


In [71]:
# Element wise multiplication
print(arr*arr2)

[[ 1  4  3]
 [16  0 36]
 [56  1  0]]


In [75]:
# Element wise square root
sq = np.array([[1,25,4],[9,49,16],[64,81,100]])
print(sq)
print()
print(np.sqrt(sq))

[[  1  25   4]
 [  9  49  16]
 [ 64  81 100]]

[[ 1.  5.  2.]
 [ 3.  7.  4.]
 [ 8.  9. 10.]]


In [76]:
sq.sum()

349

In [77]:
sq.max()

100

In [78]:
sq.min()

1

In [84]:
print(sq)
np.where(sq>49) 
# First Array Row index & second is column index
# that means (2,0) ,(2,1) ,(2,2) elements are > 49

[[  1  25   4]
 [  9  49  16]
 [ 64  81 100]]


(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [86]:
np.where(sq==16)
# at array index (1,2) element is equal to 16

(array([1], dtype=int64), array([2], dtype=int64))

In [87]:
np.count_nonzero(sq) # returns number of non zero elements

9

In [90]:
np.nonzero(sq) # returns all indeces of non zero elements

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [94]:
np.array2string(sq)
print(type(np.array2string(sq)))

<class 'str'>
