# Numpy Tutorial

In [1]:
import numpy as np # importing numpy module as np for the currrent file

In [2]:
# What is a numpy array?
# An array is a central data structure of the NumPy library. 
# An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element.


# Initialize the numpy array

example_array = np.array([1,2,3,4,5,6])
print(example_array)

# Initialize multi-dimensional array
example_MDarray = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(example_MDarray)
# Print a specific element
print(f"Element is = {example_MDarray[0][2]}") # Output = 3

[1 2 3 4 5 6]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Element is = 3


In [3]:
# To create a array with all element initialized as ZERO
print(np.zeros(5))
# To create a array with all element initialized as ONE
print(np.ones(5))
# You can create an array with a range of elements that means 0 - (n-1)
print(np.arange(5))
# And even an array that contains a range of evenly spaced intervals. To do this, you will specify the first number, 
# last number, and the step size.
print(np.arange(0,10,2))


[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 1 2 3 4]
[0 2 4 6 8]


#### Specifying the dtype explicitly

In [4]:
# While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword.
example_array = np.ones(5, dtype=np.int8)
print(example_array)

[1 1 1 1 1]


### Adding Removing Sorting ELements

In [5]:
# To sort an array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr = np.sort(arr)
print(arr)
# To concatenate the array
a = np.array([1,4,3,2])
b = np.array([5,8,7,6])
c = np.concatenate((a,b)) # inner brackets () are important otherwise it will throw an error
print(c)

[1 2 3 4 5 6 7 8]
[1 4 3 2 5 8 7 6]


In [6]:
# ndarray.ndim will tell you the number of axes, or dimensions, of the array.
arr = np.array([[1,7,9,0,],[5,6,10,2]])
print(arr.ndim) # returns 2 as it is a 2 dimensional array
# ndarray.size will tell you the total number of elements of the array.
print(arr.size)
# ndarray.shape will display a tuple of integers that indicate the number of elements stored along each 
# dimension of the array. 
# If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).
print(arr.shape)
# Can you reshape an array. Answer is YES.
arr = np.array([1,2,3,4,5,6,7,8])
print("Reshape into 4 rows 2 columns")
arr = arr.reshape(4,2) # reshape into 4 rows 2 columns
print(arr)
print("Reshape into 2 rows 4 columns")
arr = arr.reshape(2,4) # reshape into 2 rows 4 columns
print(arr)

2
8
(2, 4)
Reshape into 4 rows 2 columns
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Reshape into 2 rows 4 columns
[[1 2 3 4]
 [5 6 7 8]]


### Indexing and Slicing

In [7]:
# You can index and slice NumPy arrays in the same ways you can slice Python lists.
slice_example = np.array([1,2,3,4,5,6])
print(slice_example[1:4]) # Index No: 1 to (4-1)
print(slice_example[:4])  # Default starting point is index no 0
print(slice_example[4:])  # Default ending point is index no (array-length - 1)
print(slice_example[-2:6]) # Negative slicing means (array-length - negative number)
# slice_example[-2:6] = slice_example[6-2:6] = slice_example[4:6]

[2 3 4]
[1 2 3 4]
[5 6]
[5 6]


In [8]:
arr = np.array([[1 , 2, 3, 4], [9, 10, 11, 12], [5, 6, 7, 8]])
# You can easily print all of the values in the array that are less than 5.
print("Elements greater than or equal to 10")
print(arr[arr >= 10])
print("Elements lesser than 5")
print(arr[arr < 5])
# Or you can select elements that satisfy two conditions using the & and | operators:
ans = arr[(arr < 10) & (arr > 5)] # inner brackets are important
print("Elements lesser than 10 and greater than 5")
print(ans)

Elements greater than or equal to 10
[10 11 12]
Elements lesser than 5
[1 2 3 4]
Elements lesser than 10 and greater than 5
[9 6 7 8]


In [9]:
# You can copy one array to another variable
arr = np.array([1,2,3,4,5,6])
copy_arr = arr.copy()
print(copy_arr)

[1 2 3 4 5 6]


### Basic array operations
#### This section covers addition, subtraction, multiplication, division, and more

In [10]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,9,8])
add = arr1 + arr2
print(f"Addition of 1-D array {add}")
sub = arr2-arr1
print(f"Subtraction of 1-D array {sub}")
mul = arr1*arr2
print(f"Multiplication of 1-D array {mul}")
div = arr2/arr1
print(f"Multiplication of 1-D array {div}")
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
add = arr1 + arr2
print(f"Addition of 2-D array \n{add}")


Addition of 1-D array [ 6  8 12 12]
Subtraction of 1-D array [4 4 6 4]
Multiplication of 1-D array [ 5 12 27 32]
Multiplication of 1-D array [5. 3. 3. 2.]
Addition of 2-D array 
[[ 2  4  6  8]
 [10 12 14 16]]


In [11]:
# Sum of elements in row-wise (axis = 0)
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr.sum(axis=0))
'''
Axis = 0 that means row-wise elements sum
1   2   3
+   +   +
4   5   6
+   +   +
7   8   9
=   =   =   
12  15  18
Axis = 1 that means column-wise elements sum
1 + 2 + 3 = 6
4 + 5 + 6 = 15
7 + 8 + 9 = 24
'''
print(arr.sum(axis=1))
# Sum of all elements in the array
print(arr.sum())
# If we want to scaler multiply with the array we can do it
print("Scaler Multiplication")
print(arr * 2)

[12 15 18]
[ 6 15 24]
45
Scaler Multiplication
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


#### More useful array operations

In [12]:
arr = np.array([
    [1,3,7],
    [6,9,4],
    [8,5,2]
])
print(arr.max())
print(arr.min())
print(arr.max(axis=0)) # Row wise max element
print(arr.max(axis=1)) # Column wise max element

9
1
[8 9 7]
[7 9 8]


In [13]:
arr = np.array([
    [1,3,7],
    [6,9,4],
    [8,5,2]
])
# Transpose the array
print(arr.transpose())

[[1 6 8]
 [3 9 5]
 [7 4 2]]


In [14]:
# We can perform some interesting operations with unique method in NUMPY library
arr = np.array([1,1,8,1,2,2,9,7,5,7,10,1,2])
print(np.unique(arr)) # returns list of unique elements
occurance = np.unique(arr,return_counts=True) 
# print(occurance) # returns a list of unique elements & their occurances
print(occurance[1])
# To get the indices of unique values
index = np.unique(arr,return_index=True)
print(np.sort(index[1])) # printing in sorted ordered fashion

[ 1  2  5  7  8  9 10]
[4 3 1 2 1 1 1]
[ 0  2  4  6  7  8 10]


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# We can reverse the array
reversed_array = np.flip(arr)
print(reversed_array)

[8 7 6 5 4 3 2 1]


In [16]:
arr = np.array([
    [1,3,7],
    [6,9,4],
    [8,5,2]
])
# Flatten the array that means make an array 1-D
print(arr.flatten())

[1 3 7 6 9 4 8 5 2]
